[project]
name = "theme-park-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Bernardo Silva", email = "bernardo.silva@ltplabs.com" }
]
requires-python = ">=3.13"
dependencies = [
    "ddgs>=9.13.0",
    "duckdb>=1.5.1",
    "langchain>=1.2.15",
    "langchain-community>=0.4.1",
    "langchain-openai>=1.1.12",
    "openai>=1.82",
    "pandas>=3.0.2",
    "plotly>=6.6.0",
    "polars>=1.39.3",
    "pydantic>=2.11",
    "python-dotenv>=1.2.2",
    "streamlit>=1.56.0",
]

[build-system]
requires = ["uv_build>=0.9.5,<0.10.0"]
build-backend = "uv_build"

[tool.uv.workspace]
members = [
    "theme-park-rag",
]

[tool.uv]
environments = ["sys_platform == 'win32'"]
